"""
BountyBlink / SolGuild Pan-European Quest Seed Catalog
88 authentic quests distributed across 8 major European metropolitan hubs:
- London (11 quests)
- Paris (11 quests)
- Berlin (11 quests)
- Madrid (11 quests)
- Rome (11 quests)
- Amsterdam (11 quests)
- Barcelona (11 quests)
- Vienna (11 quests)

Canonical categories:
1. Civil Help
2. Sensitive
3. Commercial
"""

import uuid
import datetime

def get_european_seed_quests():
    now = datetime.datetime.utcnow()
    expiry = now + datetime.timedelta(days=14)

    raw_quests = [
        # =====================================================================
        # 1. LONDON, UNITED KINGDOM (Lat: 51.5074, Lon: -0.1278)
        # =====================================================================
        {
            "title": "Designated ride companion: Soho to Shoreditch car escort",
            "category": "Civil Help",
            "instruction": "Meet patron outside The French House on Dean Street. Safely drive patron's vehicle to their designated parking bay in Shoreditch and hand keys to building concierge.",
            "target_description": "Vehicle parked in private Shoreditch bay with concierge key lockbox receipt in view",
            "place_name": "Dean Street Pub Quarter",
            "full_address": "49 Dean St, London W1D 5BE, United Kingdom",
            "city": "London",
            "country": "United Kingdom",
            "latitude": 51.5132,
            "longitude": -0.1324,
            "radius_meters": 150,
            "reward_sol": 0.045
        },
        {
            "title": "Find lost velvet sketchbook with brass clasp near Camden Lock",
            "category": "Civil Help",
            "instruction": "Search the stone canal overlook benches near Camden Lock market. Left an emerald green velvet hardbound sketchbook with brass lock latch.",
            "target_description": "Emerald velvet sketchbook with brass clasp resting on wooden bench or stone canal coping",
            "place_name": "Camden Lock Overlook",
            "full_address": "Camden Lock Pl, London NW1 8AF, United Kingdom",
            "city": "London",
            "country": "United Kingdom",
            "latitude": 51.5414,
            "longitude": -0.1466,
            "radius_meters": 100,
            "reward_sol": 0.035
        },
        {
            "title": "Elderly wheelchair assistance: Waterloo Bridge ramp to Southbank Centre",
            "category": "Civil Help",
            "instruction": "Assist elderly patron navigating the windy Waterloo bridge pedestrian ramp down to Queen Elizabeth Hall terrace level safely.",
            "target_description": "Southbank Centre yellow ramp balustrade with Waterloo Bridge arch in background",
            "place_name": "Waterloo South Access Ramp",
            "full_address": "Belvedere Rd, London SE1 8XX, United Kingdom",
            "city": "London",
            "country": "United Kingdom",
            "latitude": 51.5065,
            "longitude": -0.1165,
            "radius_meters": 120,
            "reward_sol": 0.04
        },
        {
            "title": "Retrieve prescription spectacles left on Russell Square garden bench",
            "category": "Civil Help",
            "instruction": "Inspect park benches near the central fountain café in Russell Square. Left black-frame tortoise prescription glasses inside a dark brown leather slipcase.",
            "target_description": "Brown leather glasses case with tortoiseshell spectacles on garden bench slats",
            "place_name": "Russell Square Garden Walk",
            "full_address": "Russell Square, Bloomsbury, London WC1B 5EH, United Kingdom",
            "city": "London",
            "country": "United Kingdom",
            "latitude": 51.5218,
            "longitude": -0.1261,
            "radius_meters": 100,
            "reward_sol": 0.03
        },
        {
            "title": "Discreet surveillance & license plate log of black courier van in Mayfair",
            "category": "Sensitive",
            "instruction": "Discreetly verify the commercial loading alley off Mount Street. Photograph the parked black courier van's license plate and submit a formal investigation letter detailing delivery origin and timetable.",
            "target_description": "Black logistics van rear registration plate with Mayfair alley stone paving visible",
            "place_name": "Mount Street Commercial Alley",
            "full_address": "Mount St, Mayfair, London W1K 2RN, United Kingdom",
            "city": "London",
            "country": "United Kingdom",
            "latitude": 51.5097,
            "longitude": -0.1492,
            "radius_meters": 100,
            "reward_sol": 0.06
        },
        {
            "title": "VIP close protection security escort: Liverpool Street to Bank station",
            "category": "Sensitive",
            "instruction": "Provide discreet security presence walking patron carrying sensitive financial documents along Old Broad Street to the Bank junction. Upload route timestamp photo and protective transit dossier letter.",
            "target_description": "Bank of England portico pillars and Threadneedle Street sign at conclusion of transit",
            "place_name": "City Financial Corridor",
            "full_address": "Threadneedle St, London EC2R 8AH, United Kingdom",
            "city": "London",
            "country": "United Kingdom",
            "latitude": 51.5134,
            "longitude": -0.0889,
            "radius_meters": 120,
            "reward_sol": 0.065
        },
        {
            "title": "Trace hallmark provenance on antique silver pocket watch at Portobello",
            "category": "Sensitive",
            "instruction": "Inspect the antique watch stall at Portobello Road. Photograph hallmark stamp inside casing and submit an investigation letter verifying silver provenance and dealer source.",
            "target_description": "Silver pocket watch open caseback showing London silversmith hallmark stamp clearly",
            "place_name": "Portobello Road Antique Market",
            "full_address": "Portobello Rd, Notting Hill, London W11 1LJ, United Kingdom",
            "city": "London",
            "country": "United Kingdom",
            "latitude": 51.5173,
            "longitude": -0.2057,
            "radius_meters": 100,
            "reward_sol": 0.055
        },
        {
            "title": "Verify identity & attire match of courier near St. Pancras Eurostar arrivals",
            "category": "Sensitive",
            "instruction": "Observe the public seating area near the bronze Lovers Statue at St. Pancras. Photograph the individual wearing a navy wool overcoat with leather briefcase and submit observation dossier.",
            "target_description": "St. Pancras clock tower arcade and individual matching description in public waiting zone",
            "place_name": "St. Pancras Grand Terrace",
            "full_address": "Euston Rd, London N1C 4QP, United Kingdom",
            "city": "London",
            "country": "United Kingdom",
            "latitude": 51.5318,
            "longitude": -0.1243,
            "radius_meters": 100,
            "reward_sol": 0.05
        },
        {
            "title": "UGC promotional reel at Borough Market sourdough artisan bakery",
            "category": "Commercial",
            "instruction": "Purchase one freshly baked rosemary sourdough loaf. Film a 10-second vertical aesthetic showcase under the green market roof with bakery brand packaging in focus.",
            "target_description": "Crusty golden sourdough loaf with Borough Market heritage green ironwork roof visible",
            "place_name": "Borough Market Bakery Arcade",
            "full_address": "8 Southwark St, London SE1 1TL, United Kingdom",
            "city": "London",
            "country": "United Kingdom",
            "latitude": 51.5055,
            "longitude": -0.0910,
            "radius_meters": 100,
            "reward_sol": 0.035
        },
        {
            "title": "Flagship luxury storefront window display audit on Regent Street",
            "category": "Commercial",
            "instruction": "Capture daytime eye-level commercial photography of the autumn window display at the Regent Street flagship boutique. Verify lighting alignment and logo clarity.",
            "target_description": "Curved Regent Street neoclassical stone facade with brand window mannequins and display lighting",
            "place_name": "Regent Street Curve",
            "full_address": "Regent St, Mayfair, London W1B 5AH, United Kingdom",
            "city": "London",
            "country": "United Kingdom",
            "latitude": 51.5118,
            "longitude": -0.1388,
            "radius_meters": 100,
            "reward_sol": 0.03
        },
        {
            "title": "Coffee house aesthetic video & menu board photography in Covent Garden",
            "category": "Commercial",
            "instruction": "Take high-resolution photography of the daily single-origin espresso slate menu board and a styled flat-lay of the ceramic cappuccino cup on the wooden bar.",
            "target_description": "Chalk slate menu board with coffee offerings and ceramic cup on marble coffee bar",
            "place_name": "Covent Garden Piazza Espresso Bar",
            "full_address": "The Market, Covent Garden, London WC2E 8RF, United Kingdom",
            "city": "London",
            "country": "United Kingdom",
            "latitude": 51.5117,
            "longitude": -0.1228,
            "radius_meters": 100,
            "reward_sol": 0.035
        },

        # =====================================================================
        # 2. PARIS, FRANCE (Lat: 48.8566, Lon: 2.3522)
        # =====================================================================
        {
            "title": "Find lost Siamese cat 'Lumi' near Montmartre Sacré-Cœur steps",
            "category": "Civil Help",
            "instruction": "Search the garden terraces and winding cobblestone stairs near the base of Sacré-Cœur. Looking for a blue-eyed cream Siamese cat with brown ears and a blue silk collar.",
            "target_description": "Siamese cat with cream fur, dark points, and blue collar near garden wall",
            "place_name": "Square Louise Michel Steps",
            "full_address": "6 Pl. Saint-Pierre, 75018 Paris, France",
            "city": "Paris",
            "country": "France",
            "latitude": 48.8858,
            "longitude": 2.3444,
            "radius_meters": 150,
            "reward_sol": 0.04
        },
        {
            "title": "Assist wheelchair patron across Louvre carousel access ramp",
            "category": "Civil Help",
            "instruction": "Meet elderly visitor by the Arc de Triomphe du Carrousel and guide wheelchair smoothly across the gravel courtyard to the subterranean glass pyramid elevator.",
            "target_description": "Louvre glass inverted pyramid skylight entrance and accessible elevator platform",
            "place_name": "Jardin du Carrousel",
            "full_address": "Pl. du Carrousel, 75001 Paris, France",
            "city": "Paris",
            "country": "France",
            "latitude": 48.8617,
            "longitude": 2.3328,
            "radius_meters": 120,
            "reward_sol": 0.045
        },
        {
            "title": "Retrieve burgundy leather purse lost in Place des Vosges arcade",
            "category": "Civil Help",
            "instruction": "Check the red-brick stone arcade walkway and courtyard fountain perimeter. Left a burgundy leather shoulder purse with golden clasp on stone bench.",
            "target_description": "Burgundy leather shoulder purse with golden clasp on bench or stone pillar base",
            "place_name": "Place des Vosges North Arcade",
            "full_address": "Place des Vosges, 75004 Paris, France",
            "city": "Paris",
            "country": "France",
            "latitude": 48.8554,
            "longitude": 2.3656,
            "radius_meters": 100,
            "reward_sol": 0.035
        },
        {
            "title": "Water balcony flowerbeds and inspect shutter locks in Le Marais",
            "category": "Civil Help",
            "instruction": "Access 3rd floor courtyard balcony to water geranium planter boxes and verify all four wooden exterior window shutters are bolted shut against rain.",
            "target_description": "Watered geranium window boxes with dark green wooden shutters latched shut",
            "place_name": "Rue des Rosiers Courtyard",
            "full_address": "Rue des Rosiers, 75004 Paris, France",
            "city": "Paris",
            "country": "France",
            "latitude": 48.8572,
            "longitude": 2.3598,
            "radius_meters": 80,
            "reward_sol": 0.03
        },
        {
            "title": "Document serial numbers & origin stamp on vintage timepiece collection in Saint-Germain",
            "category": "Sensitive",
            "instruction": "Inspect antique horology boutique on Rue de Bac. Photograph inner case engraving of 1950s French chronometer and submit origin validation report citing dealer ledger.",
            "target_description": "Mechanical chronometer open caseback revealing movement caliber and French hallmark",
            "place_name": "Saint-Germain Antique Quarter",
            "full_address": "Rue du Bac, 75007 Paris, France",
            "city": "Paris",
            "country": "France",
            "latitude": 48.8569,
            "longitude": 2.3275,
            "radius_meters": 100,
            "reward_sol": 0.055
        },
        {
            "title": "Security companion escort along Canal Saint-Martin quayside at midnight",
            "category": "Sensitive",
            "instruction": "Provide discrete protective escort for patron traveling from Quai de Valmy footbridge to Gare de l'Est. Submit timestamped checkpoint photo and transit safety letter.",
            "target_description": "Canal Saint-Martin iron footbridge arched structure illuminated at night",
            "place_name": "Quai de Valmy Walkway",
            "full_address": "Quai de Valmy, 75010 Paris, France",
            "city": "Paris",
            "country": "France",
            "latitude": 48.8719,
            "longitude": 2.3652,
            "radius_meters": 120,
            "reward_sol": 0.06
        },
        {
            "title": "Background observation on fine art gallery courier van on Rue de Seine",
            "category": "Sensitive",
            "instruction": "Photograph the logistics registration and cargo door seals of private art transport van parked near art gallery. Submit full investigation letter on dispatch origin.",
            "target_description": "Rear cargo doors of transport van showing security seal number and French registration",
            "place_name": "Rue de Seine Art District",
            "full_address": "Rue de Seine, 75006 Paris, France",
            "city": "Paris",
            "country": "France",
            "latitude": 48.8542,
            "longitude": 2.3364,
            "radius_meters": 100,
            "reward_sol": 0.05
        },
        {
            "title": "Locate and photograph specific coat-of-arms stonework origin in Latin Quarter",
            "category": "Sensitive",
            "instruction": "Locate carved 17th-century heraldic shield above doorway in Rue Saint-Séverin. Photograph emblem details and submit historical origin verification report.",
            "target_description": "Carved limestone heraldic shield with fleur-de-lis motif above stone lintel",
            "place_name": "Rue Saint-Séverin Heritage Lintel",
            "full_address": "Rue Saint-Séverin, 75005 Paris, France",
            "city": "Paris",
            "country": "France",
            "latitude": 48.8524,
            "longitude": 2.3453,
            "radius_meters": 100,
            "reward_sol": 0.045
        },
        {
            "title": "Artisan pistachio tart showcase photo & tasting reel at Belleville bakery",
            "category": "Commercial",
            "instruction": "Purchase seasonal pistachio tart from the bakery display, place it by the window terrace with shop signage in background, and capture a sharp commercial photo.",
            "target_description": "Pistachio pastry confection in packaging with Boulangerie Belleville storefront lettering in focus",
            "place_name": "Boulangerie Artisanale Belleville",
            "full_address": "38 Rue de Belleville, 75020 Paris, France",
            "city": "Paris",
            "country": "France",
            "latitude": 48.8722,
            "longitude": 2.3811,
            "radius_meters": 100,
            "reward_sol": 0.03
        },
        {
            "title": "Niche perfume boutique storefront photoshoot at Palais-Royal arcade",
            "category": "Commercial",
            "instruction": "Capture eye-level commercial photos of luxury perfume bottle display inside Palais-Royal colonnade arcade, highlighting natural morning light on glass flacons.",
            "target_description": "Palais-Royal stone colonnade with luxury perfume flacons in boutique window display",
            "place_name": "Galerie de Valois Arcade",
            "full_address": "Galerie de Valois, 75001 Paris, France",
            "city": "Paris",
            "country": "France",
            "latitude": 48.8647,
            "longitude": 2.3382,
            "radius_meters": 100,
            "reward_sol": 0.035
        },
        {
            "title": "Vintage fashion boutique window display and interior apparel UGC video in Oberkampf",
            "category": "Commercial",
            "instruction": "Record an aesthetic 15-second slow pan video showcasing curated autumn trench coats and silk scarves displayed on mannequins in vintage concept store.",
            "target_description": "Storefront display with retro trench coats, silk scarves, and boutique neon signage",
            "place_name": "Rue Oberkampf Boutique",
            "full_address": "Rue Oberkampf, 75011 Paris, France",
            "city": "Paris",
            "country": "France",
            "latitude": 48.8649,
            "longitude": 2.3736,
            "radius_meters": 100,
            "reward_sol": 0.035
        },

        # =====================================================================
        # 3. BERLIN, GERMANY (Lat: 52.5200, Lon: 13.4050)
        # =====================================================================
        {
            "title": "Find lost calico cat 'Mika' near Boxhagener Platz",
            "category": "Civil Help",
            "instruction": "Search around the park benches and chestnut trees near Boxhagener Platz. My elderly cat slipped her harness; she has a distinctive yellow bell collar and calico patches.",
            "target_description": "Calico cat with white chest, ginger patches, and yellow bell collar resting near grass or bench",
            "place_name": "Boxhagener Platz Square",
            "full_address": "Boxhagener Pl. 1, 10245 Berlin, Germany",
            "city": "Berlin",
            "country": "Germany",
            "latitude": 52.5113,
            "longitude": 13.4593,
            "radius_meters": 150,
            "reward_sol": 0.035
        },
        {
            "title": "Help my grandpa on wheelchair navigate Warschauer U-Bahn elevator",
            "category": "Civil Help",
            "instruction": "Meet my grandpa and assist with wheelchair navigation through the busy station ramp and elevator entrance to the yellow U1/U3 platform.",
            "target_description": "Warschauer Str. station accessible entrance glass elevator tower and yellow U-Bahn sign",
            "place_name": "Warschauer Str. Barrier-Free Access",
            "full_address": "Revaler Str. 99, 10245 Berlin, Germany",
            "city": "Berlin",
            "country": "Germany",
            "latitude": 52.5085,
            "longitude": 13.4522,
            "radius_meters": 150,
            "reward_sol": 0.04
        },
        {
            "title": "Designated driver companion: Friedrichshain club district vehicle escort",
            "category": "Civil Help",
            "instruction": "Meet patron near Revaler Straße after evening event. Drive patron's VW Golf safely to their residence parking lot in Prenzlauer Berg.",
            "target_description": "Vehicle parked in residential courtyard with courtyard house number plaque visible",
            "place_name": "RAW-Gelände Main Gate",
            "full_address": "Revaler Str. 99, 10245 Berlin, Germany",
            "city": "Berlin",
            "country": "Germany",
            "latitude": 52.5074,
            "longitude": 13.4550,
            "radius_meters": 150,
            "reward_sol": 0.045
        },
        {
            "title": "Retrieve forgotten cycling pannier bag near Mauerpark flea market",
            "category": "Civil Help",
            "instruction": "Search the grass slope benches near the amphitheater in Mauerpark. A waterproof yellow Ortlieb bike pannier bag was left hooked on wooden bench railing.",
            "target_description": "Bright yellow waterproof bicycle pannier bag hooked on wooden park bench",
            "place_name": "Mauerpark Amphitheater Slope",
            "full_address": "Bernauer Str. 63, 13355 Berlin, Germany",
            "city": "Berlin",
            "country": "Germany",
            "latitude": 52.5437,
            "longitude": 13.4027,
            "radius_meters": 120,
            "reward_sol": 0.03
        },
        {
            "title": "Document clandestine graffiti tagger identity stencil along Spree canal wall",
            "category": "Sensitive",
            "instruction": "Discreetly photograph the newly sprayed stencil signature and paint residue near the Schillingbrücke embankment. Submit photo and investigation letter identifying artist tag lineage.",
            "target_description": "Fresh spray-paint stencil signature on concrete embankment with bridge ironwork in background",
            "place_name": "Schillingbrücke Embankment",
            "full_address": "Schillingbrücke, 10243 Berlin, Germany",
            "city": "Berlin",
            "country": "Germany",
            "latitude": 52.5088,
            "longitude": 13.4326,
            "radius_meters": 100,
            "reward_sol": 0.055
        },
        {
            "title": "Security companion and protective walk through Görlitzer Park at dusk",
            "category": "Sensitive",
            "instruction": "Provide vigilant security escort for patron carrying high-value tech hardware walking from Wiener Straße to Falckensteinstraße. Submit timestamped checkpoint photo and security log letter.",
            "target_description": "Görlitzer Park Spreewaldplatz entrance gate illuminated at dusk",
            "place_name": "Spreewaldplatz Park Entrance",
            "full_address": "Wiener Straße 59, 10999 Berlin, Germany",
            "city": "Berlin",
            "country": "Germany",
            "latitude": 52.4982,
            "longitude": 13.4287,
            "radius_meters": 120,
            "reward_sol": 0.06
        },
        {
            "title": "Verify manufacturer stamp & origin plate on vintage East-German motorcycle parts",
            "category": "Sensitive",
            "instruction": "Inspect custom motorcycle garage on Karl-Marx-Allee. Photograph the original MZ engine serial plate and submit investigation report validating German Democratic Republic origin.",
            "target_description": "Metal stamped engine serial badge with IFA/MZ emblem and production number clearly visible",
            "place_name": "Karl-Marx-Allee Garage Arcade",
            "full_address": "Karl-Marx-Allee 78, 10243 Berlin, Germany",
            "city": "Berlin",
            "country": "Germany",
            "latitude": 52.5186,
            "longitude": 13.4411,
            "radius_meters": 100,
            "reward_sol": 0.05
        },
        {
            "title": "Discreet observation of courier exchange near Ostbahnhof freight terminal",
            "category": "Sensitive",
            "instruction": "Observe the logistics parking lot adjacent to Ostbahnhof tracks. Photograph registration of courier vehicle and submit detailed investigation dossier citing timing and package transfer details.",
            "target_description": "Rear view of white transport van parked near freight fence with rail gantry overhead",
            "place_name": "Ostbahnhof Freight Bay",
            "full_address": "Koppenstraße 3, 10243 Berlin, Germany",
            "city": "Berlin",
            "country": "Germany",
            "latitude": 52.5106,
            "longitude": 13.4348,
            "radius_meters": 100,
            "reward_sol": 0.055
        },
        {
            "title": "Independent vinyl record shop promotional reel and sleeve unboxing in Kreuzberg",
            "category": "Commercial",
            "instruction": "Record a smooth 15-second vertical video flipping through newly arrived minimal techno vinyl records at the listening station, ending with store logo neon sign.",
            "target_description": "Turntable slipmat with spinning vinyl record and record shop wall display illuminated",
            "place_name": "Oranienstraße Record Vault",
            "full_address": "Oranienstraße 185, 10999 Berlin, Germany",
            "city": "Berlin",
            "country": "Germany",
            "latitude": 52.5008,
            "longitude": 13.4182,
            "radius_meters": 100,
            "reward_sol": 0.035
        },
        {
            "title": "Craft beer taproom interior photoshoot and flight presentation in Neukölln",
            "category": "Commercial",
            "instruction": "Take high-resolution photos of a 4-glass tasting flight on wooden paddle, positioned on industrial copper bar counter with brewery logo chalkboard in background.",
            "target_description": "Four colored craft beers on wooden paddle sitting on copper bar counter with taps visible",
            "place_name": "Weserstraße Craft Taproom",
            "full_address": "Weserstraße 58, 12045 Berlin, Germany",
            "city": "Berlin",
            "country": "Germany",
            "latitude": 52.4851,
            "longitude": 13.4338,
            "radius_meters": 100,
            "reward_sol": 0.03
        },
        {
            "title": "Eco-friendly specialty coffee roastery video & packaging photo in Mitte",
            "category": "Commercial",
            "instruction": "Photograph the newly released Ethiopian roast coffee bean pouch standing on natural birch counter, highlighting the compostable seal and roast date stamp.",
            "target_description": "Matte kraft coffee bean bag with embossed label and vintage espresso grinder behind",
            "place_name": "Rosenthaler Platz Roastery",
            "full_address": "Rosenthaler Str. 36, 10178 Berlin, Germany",
            "city": "Berlin",
            "country": "Germany",
            "latitude": 52.5302,
            "longitude": 13.4014,
            "radius_meters": 100,
            "reward_sol": 0.03
        },

        # =====================================================================
        # 4. MADRID, SPAIN (Lat: 40.4168, Lon: -3.7038)
        # =====================================================================
        {
            "title": "Find lost golden retriever 'Sol' wearing red bandana in El Retiro Park",
            "category": "Civil Help",
            "instruction": "Search around the Palacio de Cristal lake and shaded chestnut avenues of El Retiro. Friendly golden retriever with red cloth bandana around neck.",
            "target_description": "Golden retriever dog with red bandana near lake edge or glass palace pillars",
            "place_name": "Palacio de Cristal Lakeside",
            "full_address": "Paseo de la República de Cuba, 4, 28009 Madrid, Spain",
            "city": "Madrid",
            "country": "Spain",
            "latitude": 40.4136,
            "longitude": -3.6820,
            "radius_meters": 150,
            "reward_sol": 0.04
        },
        {
            "title": "Designated driver: Drive patron's vehicle safely home from Malasaña tapas tour",
            "category": "Civil Help",
            "instruction": "Meet patron at Plaza del Dos de Mayo. Drive patron's Seat León safely to their underground parking space on Calle Princesa.",
            "target_description": "Parked car in designated underground numbered bay with security gate in view",
            "place_name": "Plaza del Dos de Mayo",
            "full_address": "Pl. del Dos de Mayo, 28004 Madrid, Spain",
            "city": "Madrid",
            "country": "Spain",
            "latitude": 40.4276,
            "longitude": -3.7037,
            "radius_meters": 150,
            "reward_sol": 0.045
        },
        {
            "title": "Assist elderly resident with market groceries up steep Calle Mayor",
            "category": "Civil Help",
            "instruction": "Meet elderly resident outside Mercado de San Miguel and help carry two heavy grocery bags up the pedestrian slope to their residential doorway on Calle Mayor.",
            "target_description": "Historic wooden doorway and brass knocker on Calle Mayor with resident's cart",
            "place_name": "Calle Mayor West Portals",
            "full_address": "Calle Mayor 64, 28013 Madrid, Spain",
            "city": "Madrid",
            "country": "Spain",
            "latitude": 40.4158,
            "longitude": -3.7103,
            "radius_meters": 100,
            "reward_sol": 0.035
        },
        {
            "title": "Check apartment terrace plants and storm drainage in Chamberí district",
            "category": "Civil Help",
            "instruction": "Water potted bougainvillea and olive tree on 5th floor penthouse terrace and clear drainage grate of fallen leaves ahead of rain.",
            "target_description": "Clear terrace drain grate and watered potted olive tree with Madrid rooftops background",
            "place_name": "Chamberí Penthouse Terrace",
            "full_address": "Calle de Santa Engracia, 28010 Madrid, Spain",
            "city": "Madrid",
            "country": "Spain",
            "latitude": 40.4342,
            "longitude": -3.7001,
            "radius_meters": 80,
            "reward_sol": 0.03
        },
        {
            "title": "Verify authenticity seal & provenance of antique 1940s bullfighting poster",
            "category": "Sensitive",
            "instruction": "Inspect antique print shop on Calle del Prado. Photograph lithograph publisher imprint seal and submit investigation letter validating original Madrid printing authenticity.",
            "target_description": "Lithograph poster corner showing vintage Madrid publisher stamp and tax stamp seal",
            "place_name": "Calle del Prado Print Archive",
            "full_address": "Calle del Prado 12, 28014 Madrid, Spain",
            "city": "Madrid",
            "country": "Spain",
            "latitude": 40.4151,
            "longitude": -3.6989,
            "radius_meters": 100,
            "reward_sol": 0.055
        },
        {
            "title": "VIP security protection companion through Lavapiés backstreets after midnight",
            "category": "Sensitive",
            "instruction": "Provide vigilant close protection for client carrying confidential documents through Calle Argumosa to Plaza Tirso de Molina. Submit transit photo and safety report letter.",
            "target_description": "Tirso de Molina central statue illuminated under streetlamps at conclusion of escort",
            "place_name": "Plaza Tirso de Molina",
            "full_address": "Pl. de Tirso de Molina, 28012 Madrid, Spain",
            "city": "Madrid",
            "country": "Spain",
            "latitude": 40.4124,
            "longitude": -3.7047,
            "radius_meters": 120,
            "reward_sol": 0.06
        },
        {
            "title": "Document suspicious unbadged freight deliveries at Atocha station rear docks",
            "category": "Sensitive",
            "instruction": "Discreetly photograph the rear logistics bay of Atocha railway station. Capture license plate and company lettering on delivery trucks and submit detailed investigation dossier.",
            "target_description": "Industrial loading bay gate at Atocha with commercial truck registration plate clearly visible",
            "place_name": "Atocha Logistics Bay",
            "full_address": "Calle de Méndez Álvaro, 28045 Madrid, Spain",
            "city": "Madrid",
            "country": "Spain",
            "latitude": 40.4045,
            "longitude": -3.6896,
            "radius_meters": 100,
            "reward_sol": 0.05
        },
        {
            "title": "Photograph specific family crest stonework origin on Calle de Alcalá",
            "category": "Sensitive",
            "instruction": "Locate carved stone shield above high arch on Calle de Alcalá near Cibeles. Photograph heraldic symbols and submit investigation letter tracing municipal registry origin.",
            "target_description": "High-relief stone coat of arms above portal arch with carved crown and shield crest",
            "place_name": "Calle de Alcalá Historic Arch",
            "full_address": "Calle de Alcalá 42, 28014 Madrid, Spain",
            "city": "Madrid",
            "country": "Spain",
            "latitude": 40.4192,
            "longitude": -3.6961,
            "radius_meters": 100,
            "reward_sol": 0.045
        },
        {
            "title": "Traditional churrería hot chocolate dipping promotional video on San Ginés",
            "category": "Commercial",
            "instruction": "Order portion of hot churros with dark chocolate cup. Record a crisp 10-second close-up video of dipping steaming churro into thick chocolate with San Ginés tile sign visible.",
            "target_description": "Fresh golden churros dipping into thick porcelain cup of dark chocolate with green tile sign",
            "place_name": "Chocolatería San Ginés Alley",
            "full_address": "Pasadizo de San Ginés, 5, 28013 Madrid, Spain",
            "city": "Madrid",
            "country": "Spain",
            "latitude": 40.4170,
            "longitude": -3.7071,
            "radius_meters": 100,
            "reward_sol": 0.035
        },
        {
            "title": "Handcrafted leather boots showcase photoshoot on Gran Vía boutique",
            "category": "Commercial",
            "instruction": "Take high-contrast product photos of artisan cordovan leather boots arranged on polished walnut bench inside boutique, with Gran Vía street reflections through window.",
            "target_description": "Pair of polished brown leather boots with stitched welt and brand embossing on insole",
            "place_name": "Gran Vía Leather Emporium",
            "full_address": "Gran Vía 32, 28013 Madrid, Spain",
            "city": "Madrid",
            "country": "Spain",
            "latitude": 40.4201,
            "longitude": -3.7042,
            "radius_meters": 100,
            "reward_sol": 0.03
        },
        {
            "title": "Tapas bar signature Iberian ham carving presentation UGC video in La Latina",
            "category": "Commercial",
            "instruction": "Record maestro cortador slicing paper-thin jamón ibérico de bellota from the leg mount onto a classic white porcelain plate.",
            "target_description": "Cured jamón leg on wooden ham holder with paper-thin slice being plated onto white porcelain",
            "place_name": "Calle Cava Baja Tapas Bar",
            "full_address": "Calle de la Cava Baja 17, 28005 Madrid, Spain",
            "city": "Madrid",
            "country": "Spain",
            "latitude": 40.4128,
            "longitude": -3.7100,
            "radius_meters": 100,
            "reward_sol": 0.035
        },

        # =====================================================================
        # 5. ROME, ITALY (Lat: 41.9028, Lon: 12.4964)
        # =====================================================================
        {
            "title": "Retrieve lost brown leather wallet dropped near Trevi fountain marble steps",
            "category": "Civil Help",
            "instruction": "Check the lower travertine stone steps facing the right side of Trevi fountain. Left a dark brown leather bi-fold wallet containing museum ticket stub.",
            "target_description": "Brown leather wallet resting against travertine step base with Trevi fountain fountain water in background",
            "place_name": "Piazza di Trevi Fountain Steps",
            "full_address": "Piazza di Trevi, 00187 Roma RM, Italy",
            "city": "Rome",
            "country": "Italy",
            "latitude": 41.9009,
            "longitude": 12.4833,
            "radius_meters": 100,
            "reward_sol": 0.04
        },
        {
            "title": "Senior companion: Escort grandmother across uneven cobblestones to Piazza Navona",
            "category": "Civil Help",
            "instruction": "Meet elderly resident on Via del Governo Vecchio and gently assist her walk across the uneven sanpietrini stone streets to the pharmacy on Piazza Navona.",
            "target_description": "Fountain of the Four Rivers obelisk and Sant'Agnese church facade at Piazza Navona arrival",
            "place_name": "Piazza Navona West Entrance",
            "full_address": "Piazza Navona, 00186 Roma RM, Italy",
            "city": "Rome",
            "country": "Italy",
            "latitude": 41.8992,
            "longitude": 12.4731,
            "radius_meters": 120,
            "reward_sol": 0.045
        },
        {
            "title": "Water terrace lemon trees and verify shutter safety in Trastevere",
            "category": "Civil Help",
            "instruction": "Access residential rooftop terrace above Piazza di Santa Maria. Water two large terracotta pots with lemon trees and ensure awning fabric is retracted and tied.",
            "target_description": "Terracotta lemon tree planters with Rome terracotta tile rooftops in view",
            "place_name": "Trastevere Rooftop Terrace",
            "full_address": "Piazza di Santa Maria in Trastevere, 00153 Roma RM, Italy",
            "city": "Rome",
            "country": "Italy",
            "latitude": 41.8894,
            "longitude": 12.4699,
            "radius_meters": 80,
            "reward_sol": 0.035
        },
        {
            "title": "Find lost tortoiseshell kitten near Santa Maria in Trastevere piazza",
            "category": "Civil Help",
            "instruction": "Search alleyways between Via della Lungaretta and church courtyard. Small tortoiseshell kitten with yellow eyes slipped through balcony grating.",
            "target_description": "Small tortoiseshell kitten resting under vine trellis or stone doorway",
            "place_name": "Via della Lungaretta Alleys",
            "full_address": "Via della Lungaretta, 00153 Roma RM, Italy",
            "city": "Rome",
            "country": "Italy",
            "latitude": 41.8899,
            "longitude": 12.4720,
            "radius_meters": 120,
            "reward_sol": 0.035
        },
        {
            "title": "Document unauthorized street vendors operating near Colosseum arches",
            "category": "Sensitive",
            "instruction": "Discreetly photograph counterfeit merchandise setups along the pedestrian plaza facing the Arch of Constantine. Submit photo and investigation letter with operating hours and lookouts.",
            "target_description": "Colosseum outer travertine arches with unauthorized vendor blankets visible on ground",
            "place_name": "Arch of Constantine Plaza",
            "full_address": "Piazza del Colosseo, 00184 Roma RM, Italy",
            "city": "Rome",
            "country": "Italy",
            "latitude": 41.8902,
            "longitude": 12.4922,
            "radius_meters": 120,
            "reward_sol": 0.055
        },
        {
            "title": "Verify provenance & minting authenticity of rare bronze Roman coin in antique dealer",
            "category": "Sensitive",
            "instruction": "Inspect antique numismatic shop on Via dei Coronari. Photograph bronze sestertius edge and portrait relief, and submit investigation letter detailing dealer provenance registry.",
            "target_description": "Ancient Roman bronze coin in protective capsule showing emperor bust relief clearly",
            "place_name": "Via dei Coronari Antiquities",
            "full_address": "Via dei Coronari, 00186 Roma RM, Italy",
            "city": "Rome",
            "country": "Italy",
            "latitude": 41.9006,
            "longitude": 12.4705,
            "radius_meters": 100,
            "reward_sol": 0.06
        },
        {
            "title": "Night security companion escort along Lungotevere riverbank paths",
            "category": "Sensitive",
            "instruction": "Escort patron safely from Ponte Sisto footbridge along the dimly lit Tiber river embankment to Isola Tiberina. Submit timestamped bridge arrival photo and security log letter.",
            "target_description": "Ponte Sisto circular stone eye aperture illuminated at night with river reflection",
            "place_name": "Ponte Sisto Embankment",
            "full_address": "Ponte Sisto, 00186 Roma RM, Italy",
            "city": "Rome",
            "country": "Italy",
            "latitude": 41.8920,
            "longitude": 12.4710,
            "radius_meters": 120,
            "reward_sol": 0.055
        },
        {
            "title": "Discreet observation and license plate confirmation of courier van near Vatican boundary",
            "category": "Sensitive",
            "instruction": "Verify the commercial logistics access alley adjacent to the Vatican walls on Via di Porta Angelica. Photograph license plate of parked white courier van and submit provenance letter.",
            "target_description": "Vatican stone bastion wall with white logistics van and visible Italian registration plate",
            "place_name": "Porta Angelica Bastion",
            "full_address": "Via di Porta Angelica, 00193 Roma RM, Italy",
            "city": "Rome",
            "country": "Italy",
            "latitude": 41.9056,
            "longitude": 12.4578,
            "radius_meters": 100,
            "reward_sol": 0.05
        },
        {
            "title": "Artisan espresso morning roast reel with barista pour in Campo de' Fiori",
            "category": "Commercial",
            "instruction": "Capture a clean 10-second vertical video showing the extraction of a rich crema espresso into a ceramic demitasse cup, with the bustling morning market visible in background.",
            "target_description": "Ceramic cup receiving espresso pour with Campo de' Fiori Giordano Bruno statue in blur background",
            "place_name": "Campo de' Fiori Historic Roaster",
            "full_address": "Piazza Campo de' Fiori, 00186 Roma RM, Italy",
            "city": "Rome",
            "country": "Italy",
            "latitude": 41.8955,
            "longitude": 12.4722,
            "radius_meters": 100,
            "reward_sol": 0.03
        },
        {
            "title": "Handmade pasta workshop cooking demonstration & dish photoshoot in Testaccio",
            "category": "Commercial",
            "instruction": "Photograph the chef plating fresh handmade cacio e pepe tossed inside a pecorino wheel onto rustic ceramic plates with pasta workshop logo visible.",
            "target_description": "Twirl of handmade tonnarelli pasta coated in pecorino and black pepper on artisan plate",
            "place_name": "Testaccio Traditional Pastificio",
            "full_address": "Via Galvani, 00153 Roma RM, Italy",
            "city": "Rome",
            "country": "Italy",
            "latitude": 41.8778,
            "longitude": 12.4789,
            "radius_meters": 100,
            "reward_sol": 0.035
        },
        {
            "title": "Artisan leather bag workshop showcase video in Monti district",
            "category": "Commercial",
            "instruction": "Record an aesthetic craftsmanship video of the leather artisan stitching vegetable-tanned leather briefcase at the wooden workbench in historic Monti shop.",
            "target_description": "Leather artisan workbench with brass tools, edge burnisher, and finished leather satchel",
            "place_name": "Via del Boschetto Leather Atelier",
            "full_address": "Via del Boschetto, 00184 Roma RM, Italy",
            "city": "Rome",
            "country": "Italy",
            "latitude": 41.8967,
            "longitude": 12.4905,
            "radius_meters": 100,
            "reward_sol": 0.03
        },

        # =====================================================================
        # 6. AMSTERDAM, NETHERLANDS (Lat: 52.3676, Lon: 4.9041)
        # =====================================================================
        {
            "title": "Fish out lost brass house keys dropped near Prinsengracht canal bridge",
            "category": "Civil Help",
            "instruction": "Search the wooden landing steps below the arched brick bridge on Prinsengracht. Set of three brass keys on blue braided lanyard dropped near mooring pole.",
            "target_description": "Brass keys on blue lanyard resting on wooden landing step next to canal water",
            "place_name": "Prinsengracht Bridge Steps",
            "full_address": "Prinsengracht 263, 1016 GV Amsterdam, Netherlands",
            "city": "Amsterdam",
            "country": "Netherlands",
            "latitude": 52.3752,
            "longitude": 4.8840,
            "radius_meters": 100,
            "reward_sol": 0.04
        },
        {
            "title": "Assist tourist on tandem bike repair near Jordaan canal corner",
            "category": "Civil Help",
            "instruction": "Meet stranded couple with slipped tandem bicycle chain near Westerkerk corner. Assist with resetting chain onto rear cog and tightening chain guard.",
            "target_description": "Black tandem bicycle with reset chain leaning against brick canal balustrade",
            "place_name": "Jordaan Canal Intersection",
            "full_address": "Prinsengracht 281, 1016 GW Amsterdam, Netherlands",
            "city": "Amsterdam",
            "country": "Netherlands",
            "latitude": 52.3744,
            "longitude": 4.8835,
            "radius_meters": 120,
            "reward_sol": 0.035
        },
        {
            "title": "Designated cargo bike escort: Safe transport companion across Leidseplein",
            "category": "Civil Help",
            "instruction": "Meet patron near Leidseplein. Safely navigate their heavy electric Urban Arrow cargo bike with valuable electronics cargo to their residence in Oud-Zuid.",
            "target_description": "Electric cargo bike parked in secure private courtyard in Oud-Zuid",
            "place_name": "Leidseplein Bike Staging",
            "full_address": "Leidseplein 26, 1017 PT Amsterdam, Netherlands",
            "city": "Amsterdam",
            "country": "Netherlands",
            "latitude": 52.3639,
            "longitude": 4.8828,
            "radius_meters": 150,
            "reward_sol": 0.045
        },
        {
            "title": "Water houseboat greenhouse plants and check mooring line tension along Singel",
            "category": "Civil Help",
            "instruction": "Board moored residential houseboat on Singel canal. Water window herb planters and inspect both steel bow and stern mooring cables for proper tension.",
            "target_description": "Greenhouse window herbs on houseboat roof and secure steel mooring cleat in view",
            "place_name": "Singel Canal Mooring",
            "full_address": "Singel 420, 1016 AK Amsterdam, Netherlands",
            "city": "Amsterdam",
            "country": "Netherlands",
            "latitude": 52.3688,
            "longitude": 4.8887,
            "radius_meters": 80,
            "reward_sol": 0.03
        },
        {
            "title": "Inspect maritime shipping registry plaque at Western Docklands",
            "category": "Sensitive",
            "instruction": "Locate dry-dock warehouse in Houthavens. Photograph the brass classification society builder plaque on commercial barge hull and submit origin letter verifying Dutch port registry.",
            "target_description": "Brass shipbuilder plaque with stamped tonnage and Rotterdam shipyard registry",
            "place_name": "Houthavens Maritime Dock",
            "full_address": "Danzigerkade 15, 1013 AP Amsterdam, Netherlands",
            "city": "Amsterdam",
            "country": "Netherlands",
            "latitude": 52.3951,
            "longitude": 4.8802,
            "radius_meters": 120,
            "reward_sol": 0.055
        },
        {
            "title": "Security escort during late canal crossing from Nieuwmarkt to Waterlooplein",
            "category": "Sensitive",
            "instruction": "Provide discreet protective presence for courier walking across dark canal bridges after midnight. Submit timestamped checkpoint photo and security log letter.",
            "target_description": "Waterlooplein bridge iron lamp post and canal surface reflection at night",
            "place_name": "Waterlooplein Bridge Passage",
            "full_address": "Waterlooplein 1, 1011 PG Amsterdam, Netherlands",
            "city": "Amsterdam",
            "country": "Netherlands",
            "latitude": 52.3678,
            "longitude": 4.9015,
            "radius_meters": 120,
            "reward_sol": 0.06
        },
        {
            "title": "Verify provenance of Dutch Masters oil sketch in Spiegelkwartier antique gallery",
            "category": "Sensitive",
            "instruction": "Examine small 17th-century oil sketch on oak panel in Spiegelkwartier art shop. Photograph rear panel seal and submit investigation report validating collector lineage.",
            "target_description": "Oak wood panel back with red wax collector seal and Dutch handwritten inventory ink",
            "place_name": "Spiegelkwartier Art Corridor",
            "full_address": "Nieuwe Spiegelstraat 32, 1017 DG Amsterdam, Netherlands",
            "city": "Amsterdam",
            "country": "Netherlands",
            "latitude": 52.3625,
            "longitude": 4.8882,
            "radius_meters": 100,
            "reward_sol": 0.065
        },
        {
            "title": "Discreet surveillance of suspected bicycle theft fencing spot near Sloterdijk",
            "category": "Sensitive",
            "instruction": "Discreetly observe the bicycle rack underpass on the north side of Sloterdijk station. Photograph van loading cycles and submit detailed investigation dossier with plate details.",
            "target_description": "Underpass bike racks with cargo van registration plate clearly visible",
            "place_name": "Sloterdijk North Underpass",
            "full_address": "Piëmont 1, 1043 AK Amsterdam, Netherlands",
            "city": "Amsterdam",
            "country": "Netherlands",
            "latitude": 52.3892,
            "longitude": 4.8378,
            "radius_meters": 120,
            "reward_sol": 0.055
        },
        {
            "title": "Botanical tulip boutique promotional reel and floral bouquet photoshoot",
            "category": "Commercial",
            "instruction": "Film a 10-second vertical aesthetic showcase of rare dark purple tulip arrangements displayed in ceramic Dutch Delft vases inside boutique on Herengracht.",
            "target_description": "Delft blue and white porcelain vase holding dark purple tulips with canal window in background",
            "place_name": "Herengracht Florist Salon",
            "full_address": "Herengracht 386, 1016 CJ Amsterdam, Netherlands",
            "city": "Amsterdam",
            "country": "Netherlands",
            "latitude": 52.3694,
            "longitude": 4.8860,
            "radius_meters": 100,
            "reward_sol": 0.035
        },
        {
            "title": "Vintage clothing storefront display audit in De Pijp concept store",
            "category": "Commercial",
            "instruction": "Capture daytime eye-level commercial photos of retro leather jackets and graphic silk shirts displayed on wooden mannequins in shop window on Gerard Doustraat.",
            "target_description": "Vintage boutique storefront with curated leather jackets, neon brand sign, and brick facade",
            "place_name": "Gerard Doustraat Boutique",
            "full_address": "Gerard Doustraat 76, 1072 VW Amsterdam, Netherlands",
            "city": "Amsterdam",
            "country": "Netherlands",
            "latitude": 52.3569,
            "longitude": 4.8912,
            "radius_meters": 100,
            "reward_sol": 0.03
        },
        {
            "title": "Dutch stroopwafel live iron press demonstration video in Albert Cuyp market",
            "category": "Commercial",
            "instruction": "Record a mouth-watering 15-second video of fresh warm caramel being spread between steaming waffle wafers at the famous market stand.",
            "target_description": "Waffle iron with golden stroopwafel being sliced open and coated with rich warm caramel",
            "place_name": "Albert Cuyp Market Stand",
            "full_address": "Albert Cuypstraat 182, 1073 BL Amsterdam, Netherlands",
            "city": "Amsterdam",
            "country": "Netherlands",
            "latitude": 52.3558,
            "longitude": 4.8962,
            "radius_meters": 100,
            "reward_sol": 0.035
        },

        # =====================================================================
        # 7. BARCELONA, SPAIN (Lat: 41.3879, Lon: 2.1699)
        # =====================================================================
        {
            "title": "Search for lost camera drone near Park Güell stone viaduct pathway",
            "category": "Civil Help",
            "instruction": "Search the pine trees and stone slanting pillars of the lower viaduct at Park Güell. Small grey DJI drone had emergency landing on stone balustrade ledge.",
            "target_description": "Folded grey camera drone resting on stone balustrade with pine branches in view",
            "place_name": "Park Güell Stone Viaduct",
            "full_address": "Carrer d'Olot, 08024 Barcelona, Spain",
            "city": "Barcelona",
            "country": "Spain",
            "latitude": 41.4145,
            "longitude": 2.1527,
            "radius_meters": 120,
            "reward_sol": 0.04
        },
        {
            "title": "Help grandmother with grocery haul up steep Gràcia residential stairs",
            "category": "Civil Help",
            "instruction": "Meet elderly neighbor outside Mercat de la Llibertat and carry heavy market bags up the 4 flights of narrow tiled stairs to her flat on Carrer de Verdi.",
            "target_description": "Ceramic tiled stair landing and ornate apartment door on Carrer de Verdi",
            "place_name": "Carrer de Verdi Residential Portal",
            "full_address": "Carrer de Verdi 32, 08012 Barcelona, Spain",
            "city": "Barcelona",
            "country": "Spain",
            "latitude": 41.4042,
            "longitude": 2.1578,
            "radius_meters": 100,
            "reward_sol": 0.035
        },
        {
            "title": "Designated ride escort: Drive patron car home safely from Port Olímpic",
            "category": "Civil Help",
            "instruction": "Meet patron near the marina hotel driveway. Drive patron's Audi A3 safely to their residential parking garage in Sarrià-Sant Gervasi.",
            "target_description": "Car parked in numbered garage bay with building residential badge in view",
            "place_name": "Port Olímpic Marina Driveway",
            "full_address": "Port Olímpic, 08005 Barcelona, Spain",
            "city": "Barcelona",
            "country": "Spain",
            "latitude": 41.3861,
            "longitude": 2.1972,
            "radius_meters": 150,
            "reward_sol": 0.045
        },
        {
            "title": "Check rooftop terrace garden and solar battery meter in Poblenou",
            "category": "Civil Help",
            "instruction": "Water potted cacti and citrus trees on loft building rooftop in Poblenou and verify green status LED on solar charge inverter display.",
            "target_description": "Solar inverter LCD showing green status light with Mediterranean terrace plants in foreground",
            "place_name": "Poblenou Loft Rooftop",
            "full_address": "Carrer de Pujades 100, 08005 Barcelona, Spain",
            "city": "Barcelona",
            "country": "Spain",
            "latitude": 41.3980,
            "longitude": 2.1950,
            "radius_meters": 80,
            "reward_sol": 0.03
        },
        {
            "title": "Verify authenticity & provenance of ceramic tile mosaic sample from modernist palace",
            "category": "Sensitive",
            "instruction": "Inspect antique architectural salvage workshop in Eixample. Photograph clay stamp on back of Gaudí-era ceramic trencadís tile and submit origin provenance report.",
            "target_description": "Handmade ceramic glazed mosaic tile rear clay stamp showing Barcelona workshop mark",
            "place_name": "Eixample Architectural Salvage",
            "full_address": "Carrer de Mallorca 240, 08008 Barcelona, Spain",
            "city": "Barcelona",
            "country": "Spain",
            "latitude": 41.3912,
            "longitude": 2.1610,
            "radius_meters": 100,
            "reward_sol": 0.055
        },
        {
            "title": "Security escort near Gothic Quarter alleyways at midnight",
            "category": "Sensitive",
            "instruction": "Provide vigilant protective walking accompaniment through narrow alleys of El Born and Gothic Quarter to Plaça de Sant Jaume. Submit checkpoint photo and transit log letter.",
            "target_description": "Plaça de Sant Jaume illuminated stone facade and lantern arch at midnight",
            "place_name": "Plaça de Sant Jaume Portal",
            "full_address": "Plaça de Sant Jaume, 08002 Barcelona, Spain",
            "city": "Barcelona",
            "country": "Spain",
            "latitude": 41.3828,
            "longitude": 2.1768,
            "radius_meters": 120,
            "reward_sol": 0.06
        },
        {
            "title": "Discreet observation on private courier yacht arrival at Port Vell marina",
            "category": "Sensitive",
            "instruction": "Observe private mooring berth at OneOcean Port Vell. Photograph yacht name and tender registration and submit detailed investigation letter on cargo movements.",
            "target_description": "Stern nameplate of luxury yacht berthed at marina with port registration clearly visible",
            "place_name": "Port Vell Luxury Marina",
            "full_address": "Moll d'Espanya, 08039 Barcelona, Spain",
            "city": "Barcelona",
            "country": "Spain",
            "latitude": 41.3789,
            "longitude": 2.1840,
            "radius_meters": 120,
            "reward_sol": 0.055
        },
        {
            "title": "Document unauthorized ticket touts operating near Sagrada Família facade",
            "category": "Sensitive",
            "instruction": "Discreetly photograph unofficial ticket reseller individuals operating on Carrer de Mallorca opposite nativity portal. Submit photo and investigation letter detailing timings.",
            "target_description": "Sagrada Família nativity portal in view with street corner pavement where sellers operate",
            "place_name": "Carrer de Mallorca Opposite Portal",
            "full_address": "Carrer de Mallorca 401, 08013 Barcelona, Spain",
            "city": "Barcelona",
            "country": "Spain",
            "latitude": 41.4036,
            "longitude": 2.1744,
            "radius_meters": 100,
            "reward_sol": 0.05
        },
        {
            "title": "Beachside tapas bar cocktail photoshoot & Mediterranean sunset reel",
            "category": "Commercial",
            "instruction": "Capture two styled craft cocktails on rustic wooden table with Barceloneta beach and setting sun in the background. Record a 10-second vertical reel.",
            "target_description": "Two garnished craft cocktails in crystal glassware with beach sand and sea in background",
            "place_name": "Passeig Marítim Lounge",
            "full_address": "Passeig Marítim de la Barceloneta, 08003 Barcelona, Spain",
            "city": "Barcelona",
            "country": "Spain",
            "latitude": 41.3805,
            "longitude": 2.1930,
            "radius_meters": 100,
            "reward_sol": 0.035
        },
        {
            "title": "Skateboarding brand UGC video near MACBA plaza",
            "category": "Commercial",
            "instruction": "Film dynamic 15-second skateboarding video featuring brand apparel in front of the white modern facade of the Museu d'Art Contemporani de Barcelona.",
            "target_description": "Skateboarder landing trick on smooth plaza pavement with white MACBA glass facade behind",
            "place_name": "Plaça dels Àngels MACBA",
            "full_address": "Plaça dels Àngels 1, 08001 Barcelona, Spain",
            "city": "Barcelona",
            "country": "Spain",
            "latitude": 41.3833,
            "longitude": 2.1668,
            "radius_meters": 100,
            "reward_sol": 0.035
        },
        {
            "title": "Artisan chocolate bonbon box presentation photo in El Born boutique",
            "category": "Commercial",
            "instruction": "Arrange a luxury 9-piece handmade chocolate ganache box open on marble counter with gold ribbon and artisan shop logo in focus.",
            "target_description": "Artisan chocolate box open revealing geometric bonbons with gold-leaf flakes",
            "place_name": "Carrer dels Flassaders Chocolatier",
            "full_address": "Carrer dels Flassaders 21, 08003 Barcelona, Spain",
            "city": "Barcelona",
            "country": "Spain",
            "latitude": 41.3855,
            "longitude": 2.1822,
            "radius_meters": 100,
            "reward_sol": 0.03
        },

        # =====================================================================
        # 8. VIENNA, AUSTRIA (Lat: 48.2082, Lon: 16.3738)
        # =====================================================================
        {
            "title": "Find lost wooden violin bow case near Musikverein arcade",
            "category": "Civil Help",
            "instruction": "Search the portico columns and entrance ticket lobby arcade of the Musikverein. A slender black leatherette violin bow carrying tube was left leaning against column base.",
            "target_description": "Black leatherette tubular violin bow case resting against sandstone Musikverein pillar",
            "place_name": "Musikverein Colonnade",
            "full_address": "Musikvereinsplatz 1, 1010 Wien, Austria",
            "city": "Vienna",
            "country": "Austria",
            "latitude": 48.2005,
            "longitude": 16.3725,
            "radius_meters": 100,
            "reward_sol": 0.04
        },
        {
            "title": "Wheelchair escort across Hofburg cobblestone courtyard to Spanish Riding School",
            "category": "Civil Help",
            "instruction": "Meet senior visitor near Michaelerplatz gate. Guide wheelchair gently across the bumpy inner courtyard paving to the barrier-free ramp of the Spanish Riding School.",
            "target_description": "Hofburg baroque dome portal and white accessible ramp entrance in view",
            "place_name": "Michaelerplatz Gateway",
            "full_address": "Michaelerplatz 1, 1010 Wien, Austria",
            "city": "Vienna",
            "country": "Austria",
            "latitude": 48.2078,
            "longitude": 16.3664,
            "radius_meters": 120,
            "reward_sol": 0.045
        },
        {
            "title": "Designated ride companion: Escort patron home from Grinzing wine tavern",
            "category": "Civil Help",
            "instruction": "Meet patron outside historic Heuriger in Grinzing. Safely drive patron's BMW to their residential driveway in Döbling and hand keys to family member.",
            "target_description": "Vehicle parked in private driveway with house number plate illuminated",
            "place_name": "Grinzing Heuriger Quarter",
            "full_address": "Cobenzlgasse 22, 1190 Wien, Austria",
            "city": "Vienna",
            "country": "Austria",
            "latitude": 48.2562,
            "longitude": 16.3421,
            "radius_meters": 150,
            "reward_sol": 0.045
        },
        {
            "title": "Water winter conservatory plants and check heating in Neubau townhouse",
            "category": "Civil Help",
            "instruction": "Access private inner courtyard glasshouse in Neubau. Water rare orchids and verify digital thermometer reading is above 18 degrees Celsius.",
            "target_description": "Glasshouse digital thermostat display showing temperature reading with blooming orchids",
            "place_name": "Neubau Glasshouse Courtyard",
            "full_address": "Neubaugasse 45, 1070 Wien, Austria",
            "city": "Vienna",
            "country": "Austria",
            "latitude": 48.2030,
            "longitude": 16.3488,
            "radius_meters": 80,
            "reward_sol": 0.035
        },
        {
            "title": "Verify provenance seal on rare 18th-century musical manuscript in antique bookstore",
            "category": "Sensitive",
            "instruction": "Inspect antique antiquariat on Wollzeile. Photograph the archival ink seal and watermark on 18th-century sheet music manuscript, and submit provenance verification report.",
            "target_description": "Hand-scored classical musical sheet showing archival red ink stamp and paper watermark",
            "place_name": "Wollzeile Antiquariat",
            "full_address": "Wollzeile 16, 1010 Wien, Austria",
            "city": "Vienna",
            "country": "Austria",
            "latitude": 48.2091,
            "longitude": 16.3770,
            "radius_meters": 100,
            "reward_sol": 0.06
        },
        {
            "title": "Discreet VIP security escort for high-value antique jewelry transfer to Dorotheum",
            "category": "Sensitive",
            "instruction": "Provide vigilant security escort for client carrying insured jewelry casket from Kärntner Ring to the Dorotheum auction house entrance. Submit checkpoint photo and custody transfer letter.",
            "target_description": "Dorotheum auction house neoclassical bronze portal doors with street plaque visible",
            "place_name": "Dorotheum Auction House Gate",
            "full_address": "Dorotheergasse 17, 1010 Wien, Austria",
            "city": "Vienna",
            "country": "Austria",
            "latitude": 48.2064,
            "longitude": 16.3689,
            "radius_meters": 100,
            "reward_sol": 0.065
        },
        {
            "title": "Night surveillance of unauthorized access to historic courtyard in Spittelberg",
            "category": "Sensitive",
            "instruction": "Discreetly monitor the Biedermeier residential passageway between Spittelberggasse and Schrankgasse between 23:00 and 01:00. Photograph trespassers and submit full surveillance report.",
            "target_description": "Cobblestone Biedermeier alleyway with wrought-iron gate and lantern light",
            "place_name": "Spittelberg Historic Passage",
            "full_address": "Spittelberggasse 12, 1070 Wien, Austria",
            "city": "Vienna",
            "country": "Austria",
            "latitude": 48.2040,
            "longitude": 16.3551,
            "radius_meters": 100,
            "reward_sol": 0.055
        },
        {
            "title": "Photograph and trace manufacture mark on Imperial porcelain cup origin",
            "category": "Sensitive",
            "instruction": "Examine hand-painted porcelain cup at antique dealer on Herrengasse. Photograph blue beehive underglaze mark on underside and submit historical origin investigation letter.",
            "target_description": "Blue underglaze shield/beehive mark stamped on base of white porcelain teacup",
            "place_name": "Herrengasse Antique Cabinet",
            "full_address": "Herrengasse 6, 1010 Wien, Austria",
            "city": "Vienna",
            "country": "Austria",
            "latitude": 48.2096,
            "longitude": 16.3660,
            "radius_meters": 100,
            "reward_sol": 0.05
        },
        {
            "title": "Traditional Viennese Sachertorte and melange coffee promotional photoshoot",
            "category": "Commercial",
            "instruction": "Capture an iconic culinary photo of a slice of dark chocolate Sachertorte with unsweetened whipped cream alongside a hot Melange coffee in silver cup tray.",
            "target_description": "Slice of chocolate Sachertorte with chocolate medallion and whipped cream on marble table",
            "place_name": "Philharmonikerstraße Coffee Salon",
            "full_address": "Philharmoniker Str. 4, 1010 Wien, Austria",
            "city": "Vienna",
            "country": "Austria",
            "latitude": 48.2038,
            "longitude": 16.3698,
            "radius_meters": 100,
            "reward_sol": 0.035
        },
        {
            "title": "Luxury porcelain figurine window display audit on Kärntner Straße",
            "category": "Commercial",
            "instruction": "Take sharp eye-level commercial photos of the illuminated autumn window display at the luxury porcelain flagship store on Kärntner Straße.",
            "target_description": "Window display featuring hand-painted porcelain sculptures with crystal chandelier lighting",
            "place_name": "Kärntner Straße Flagship",
            "full_address": "Kärntner Str. 26, 1010 Wien, Austria",
            "city": "Vienna",
            "country": "Austria",
            "latitude": 48.2061,
            "longitude": 16.3712,
            "radius_meters": 100,
            "reward_sol": 0.03
        },
        {
            "title": "Boutique classical luthier workshop crafting video in Josefstadt",
            "category": "Commercial",
            "instruction": "Record an intimate 15-second craftsmanship video of master violin maker carving the spruce top plate of a cello in wood-scented Josefstadt workshop.",
            "target_description": "Master luthier hands carving wooden cello scroll with wood shavings on antique workbench",
            "place_name": "Josefstadt Luthier Atelier",
            "full_address": "Lange Gasse 34, 1080 Wien, Austria",
            "city": "Vienna",
            "country": "Austria",
            "latitude": 48.2105,
            "longitude": 16.3508,
            "radius_meters": 100,
            "reward_sol": 0.035
        }
    ]

    quests = []
    for q in raw_quests:
        quests.append({
            "id": str(uuid.uuid4()),
            "title": q["title"],
            "category": q["category"],
            "instruction": q["instruction"],
            "target_description": q["target_description"],
            "forbidden_description": "Unrelated image, computer screen, indoor selfie, or fabricated photo",
            "place_name": q["place_name"],
            "full_address": q["full_address"],
            "city": q["city"],
            "country": q["country"],
            "latitude": q["latitude"],
            "longitude": q["longitude"],
            "radius_meters": q["radius_meters"],
            "photos_required": 1,
            "finish_window_minutes": 15,
            "reward_sol": q["reward_sol"],
            "poster_address": f"SolGuild_Elder_{q['city'][:4]}_DevnetKey",
            "status": "OPEN",
            "fund_tx_sig": f"GuildSeal_{q['city'][:3]}_{uuid.uuid4().hex[:12]}",
            "created_at": now,
            "expires_at": expiry
        })

    return quests
